version: '3'

services:
  app:
    build: 
      context: .
    volumes:
      - .:/home/appuser/app
      - ./.docker/zsh/powerlevel10k/.p10k.zsh:/home/python/.p10k.zsh:delegated
      - ./.docker/zsh/history:/home/python/zsh:delegated
      - ./.docker/extensoes:/home/appuser/.vscode-server

    ports:
      - "8000:8000"
